# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
   console_command.csv_import:
       class: BT\NaoBundle\Command\ImportCsvCommand
       arguments:
           - "@doctrine.orm.entity_manager"
       tags:
           { name: console.command }
