<?php

namespace BT\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserByConfirmation($confirmationToken)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.confirmationToken = :confirmationToken')
            ->setParameter('confirmationToken', $confirmationToken);

        return $qb->getQuery()->getSingleResult();
    }

    public function findForgot($forgotToken)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.forgotToken = :forgotToken')
            ->setParameter('forgotToken', $forgotToken);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findNaturalisteNoConfirm()
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.naturaliste = true')
            ->andWhere('u.naturalisteConfirm = false')
            ->andWhere('u.confirm = true');
        return $qb->getQuery()->getResult();
    }

    public function countToValidate()
    {
        $qb = $this->createQueryBuilder('u')
            ->select('COUNT(u)')
            ->where('u.confirm = true')
            ->andWhere('u.naturalisteConfirm = false')
            ->andWhere('u.naturaliste = true')
            ->getQuery()
            ->getSingleScalarResult();

        return $qb;
    }

    public function findOneUser($id)
    {
        $qb = $this->createQueryBuilder('u')
            ->where('u.id = :id')
            ->setParameter('id', $id);

        return $qb->getQuery()->getSingleResult();
    }
}
