<?php

namespace BT\NaoBundle\Repository;

/**
 * BirdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBirds($term)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b.nomVern')
            ->addSelect('b.id')
            ->addSelect('b.nomComplet')
            ->where('b.nomVern LIKE :term')
            ->setParameter('term', $term . '%');
        return $qb->getQuery()->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
    }
}
