<?php

namespace BT\NaoBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBlogPosts()
    {
        $qb = $this->createQueryBuilder('p');
        return $qb->getQuery();
    }
}
